// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ReconciliationCalculatorBDD.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CalculateReconciliationForSingleAllocationHavingMultipleDeliverableGroup")]
    public partial class CalculateReconciliationForSingleAllocationHavingMultipleDeliverableGroupFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CalculateReconciliationForSingleAllocationHavingMultipleDeliverableGroup.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CalculateReconciliationForSingleAllocationHavingMultipleDeliverableGroup", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calculate Reconciliation for a funding claim group that has single allocation whi" +
            "ch in turn has a multiple deliverable group")]
        [NUnit.Framework.CategoryAttribute("SingleAllocationMultipleDelGroup")]
        public virtual void CalculateReconciliationForAFundingClaimGroupThatHasSingleAllocationWhichInTurnHasAMultipleDeliverableGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate Reconciliation for a funding claim group that has single allocation whi" +
                    "ch in turn has a multiple deliverable group", new string[] {
                        "SingleAllocationMultipleDelGroup"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Allocation Reference"});
            table1.AddRow(new string[] {
                        "ASC-1234"});
#line 5
 testRunner.Given("A funding claim reconciliation allocation group exists with name \'AdultSkills1516" +
                    "\' And Claim Type as \'MID YEAR\' that contains Allocation as follows", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Deliverable Code",
                        "Deliverable Name",
                        "Deliverable Planned Value",
                        "Deliverable Actuals to Date Value",
                        "Deliverable Forecast Remaining Delivery Value",
                        "Deliverable Exceptional Adjustments Value"});
            table2.AddRow(new string[] {
                        "1",
                        "Apprenticeships Total Funding",
                        "1000.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "2",
                        "19-23 Apprenticeships Programme Funding",
                        "0.00",
                        "100.00",
                        "50.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "3",
                        "19-23 Apprenticeships Learning Support",
                        "0.00",
                        "250.00",
                        "0.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "4",
                        "19+ Apprenticeships Learner Support",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "5",
                        "24+ Apprenticeships Programme Funding",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "6",
                        "24+ Apprenticeships Learning Support",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "7",
                        "19-23 Trailblazer Apprenticeships Programme Funding",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "8",
                        "19-23 Trailblazer Apprenticeships Learning Support",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "9",
                        "24+ Trailblazer Apprenticeships Programme Funding",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table2.AddRow(new string[] {
                        "10",
                        "24+ Trailblazer Apprenticeships Learning Support",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
#line 9
 testRunner.And("the Allocation Reference \'ASC-1234\' contains Deliverable Group \'Apprenticeships\' " +
                    "that contains following deliverables", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Deliverable Code",
                        "Deliverable Name",
                        "Deliverable Planned Value",
                        "Deliverable Actuals to Date Value",
                        "Deliverable Forecast Remaining Delivery Value",
                        "Deliverable Exceptional Adjustments Value"});
            table3.AddRow(new string[] {
                        "11",
                        "Other ASB Total Funding",
                        "500.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table3.AddRow(new string[] {
                        "12",
                        "Classroom Learning Programme Funding",
                        "0.00",
                        "300.00",
                        "0.00",
                        "-10.00"});
            table3.AddRow(new string[] {
                        "13",
                        "Classroom Learning - Learning Support",
                        "0.00",
                        "270.00",
                        "0.00",
                        "0.00"});
            table3.AddRow(new string[] {
                        "14",
                        "19-24 Traineeships Programme Funding",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table3.AddRow(new string[] {
                        "15",
                        "19-24 Traineeships Learning Support",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table3.AddRow(new string[] {
                        "16",
                        "19-24 Traineeships Learner Support",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table3.AddRow(new string[] {
                        "17",
                        "19-23 Trailblazer Apprenticeships Programme Funding",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table3.AddRow(new string[] {
                        "18",
                        "Workplace Learning Programme Funding",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
            table3.AddRow(new string[] {
                        "19",
                        "Workplace Learning - Learning Support",
                        "0.00",
                        "0.00",
                        "0.00",
                        "0.00"});
#line 22
 testRunner.And("the Allocation Reference \'ASC-1234\' contains Deliverable Group \'OtherASB\' that co" +
                    "ntains following deliverables", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "ReconcileOverDelivery",
                        "OverDeliveryDeminimis",
                        "ReconcileUnderDelivery",
                        "UnderDeliveryDeminimis"});
            table4.AddRow(new string[] {
                        "False",
                        "0.00",
                        "True",
                        "-100.00"});
#line 34
 testRunner.And("Policy Configuration Exists for Reconciliation Allocation Group \'AdultSkills1516\'" +
                    " And Claim Type Name as \'MID YEAR\' with behaviour as :", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "IsClaimToProfileCappingNeeded"});
            table5.AddRow(new string[] {
                        "False"});
#line 38
 testRunner.And("Deliverable Group \'Apprenticeships\' exists as follows", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "IsClaimToProfileCappingNeeded"});
            table6.AddRow(new string[] {
                        "True"});
#line 42
 testRunner.And("Deliverable Group \'OtherASB\' exists as follows", ((string)(null)), table6, "And ");
#line 46
 testRunner.When("reconciliation is calculated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Planned Value",
                        "Claimed Value",
                        "Capped Claimed Value",
                        "Proposed Reconciliation Value",
                        "Reconciliation Value"});
            table7.AddRow(new string[] {
                        "1500.00",
                        "960.00",
                        "900.00",
                        "-600.00",
                        "-600.00"});
#line 48
 testRunner.Then("the result should be at level of funding claim group", ((string)(null)), table7, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Allocation Reference",
                        "Planned Value",
                        "Claimed Value",
                        "Capped Claimed Value",
                        "Proposed Reconciliation Value",
                        "Reconciliation Value"});
            table8.AddRow(new string[] {
                        "ASC-1234",
                        "1500.00",
                        "960.00",
                        "900.00",
                        "-600.00",
                        "-600.00"});
#line 51
 testRunner.And("the result at the Allocation level should be", ((string)(null)), table8, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
