// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ReconciliationCalculatorBDD.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CalculateReconciliationForSingleAllocationSingleDeliverableGroup")]
    public partial class CalculateReconciliationForSingleAllocationSingleDeliverableGroupFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CalculateReconciliationForSingleAllocationSingleDeliverableGroup.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CalculateReconciliationForSingleAllocationSingleDeliverableGroup", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calculate Reconciliation for a funding claim group that has single allocation whi" +
            "ch in turn has a single deliverable group with Variance GT Deminimus")]
        [NUnit.Framework.CategoryAttribute("SingleAllocationSingleDelGroup")]
        public virtual void CalculateReconciliationForAFundingClaimGroupThatHasSingleAllocationWhichInTurnHasASingleDeliverableGroupWithVarianceGTDeminimus()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate Reconciliation for a funding claim group that has single allocation whi" +
                    "ch in turn has a single deliverable group with Variance GT Deminimus", new string[] {
                        "SingleAllocationSingleDelGroup"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Allocation Reference"});
            table1.AddRow(new string[] {
                        "CL-1234"});
#line 5
 testRunner.Given("A funding claim reconciliation allocation group exists with name \'CommunityLearni" +
                    "ng1516\' And Claim Type as \'MID YEAR\' that contains Allocation as follows", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Deliverable Code",
                        "Deliverable Name",
                        "Deliverable Planned Value",
                        "Deliverable Actuals to Date Value",
                        "Deliverable Forecast Remaining Delivery Value",
                        "Deliverable Exceptional Adjustments Value"});
            table2.AddRow(new string[] {
                        "1",
                        "Community Learning",
                        "1000.00",
                        "800.00",
                        "50.00",
                        "0.00"});
#line 8
 testRunner.And("the Allocation Reference \'CL-1234\' contains Deliverable Group \'CommunityLearning\'" +
                    " that contains following deliverables", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "ReconcileOverDelivery",
                        "OverDeliveryDeminimis",
                        "ReconcileUnderDelivery",
                        "UnderDeliveryDeminimis"});
            table3.AddRow(new string[] {
                        "False",
                        "0.00",
                        "True",
                        "-100.00"});
#line 11
 testRunner.And("Policy Configuration Exists for Reconciliation Allocation Group \'CommunityLearnin" +
                    "g1516\' And Claim Type Name as \'MID YEAR\' with behaviour as :", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "IsClaimToProfileCappingNeeded"});
            table4.AddRow(new string[] {
                        "False"});
#line 15
 testRunner.And("Deliverable Group \'CommunityLearning\' exists as follows", ((string)(null)), table4, "And ");
#line 19
 testRunner.When("reconciliation is calculated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Planned Value",
                        "Claimed Value",
                        "Capped Claimed Value",
                        "Proposed Reconciliation Value",
                        "Reconciliation Value"});
            table5.AddRow(new string[] {
                        "1000.00",
                        "850.00",
                        "850.00",
                        "-150.00",
                        "-150.00"});
#line 20
 testRunner.Then("the result should be at level of funding claim group", ((string)(null)), table5, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Allocation Reference",
                        "Planned Value",
                        "Claimed Value",
                        "Capped Claimed Value",
                        "Proposed Reconciliation Value",
                        "Reconciliation Value"});
            table6.AddRow(new string[] {
                        "CL-1234",
                        "1000.00",
                        "850.00",
                        "850.00",
                        "-150.00",
                        "-150.00"});
#line 23
 testRunner.And("the result at the Allocation level should be", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
